version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
  back_up:
    docker:
      - image: cimg/node:12.16
    steps:
      - run:
          name: Database backup
          command: npm run backup

workflows:
  heroku_deploy:
    jobs:
      - deploy
      - back_up:
          requires:
            - deploy
