version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
  schedule_backup:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: ls -a
      - run: npm install
      - run: npm install mongodb
      - run: npm install node-mongotools
      - run: npm run backup

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - build
      - schedule_backup:
          requires:
            - build
  # backup:
  #   when: << pipeline.parameters.run-schedule >>
  #   jobs:
  #     - schedule_backup
