version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
  schedule_backup:
    docker:
      - image: cimg/node:17.4.0
      - image: circleci/mongo:4.4
    steps:
      - checkout
      - run:
          name: Install MongoDB Tools
          command: |
            npm install
            sudo apt-get update
            sudo apt-get install mongodb-org-tools
      # - run: sudo apt install mongodb-org-tools
      - run: ls
      # - run: npm run backup
      # - run: mongodump --version

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - build
      - schedule_backup:
          requires:
            - build
  # backup:
  #   when: << pipeline.parameters.run-schedule >>
  #   jobs:
  #     - schedule_backup
